api:
  version: v1
  base_url: https://api.lufthansa.com

secrets:
  secret_scope: lufthansa_proxy
  password_key: password

landing:
  landing_root: "/Volumes/main/lufthansa_bronze/landing_area/tmp"

  bronse:
    bronze_root: "main.lufthansa_bronze.{entity_name}"

format:
    ts_format: "%Y%m%dT%H%M%S"
    ts_dayly_format: "%Y-%m-%d"
    ts_monthly_format: "month/%Y-%m"